In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
iris_model = LogisticRegression(max_iter=1000)


In [6]:
from sklearn.datasets import load_iris
import pandas as pd

# Load the iris dataset
iris = load_iris()

# Create a DataFrame for the features using the data and feature names
X = pd.DataFrame(iris['data'], columns=iris['feature_names'])

# Target data
y = iris['target']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [8]:
iris_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [9]:
print(iris_model.intercept_)
print(iris_model.coef_)

[  8.77675995   3.05490355 -11.83166349]
[[-0.3507686   0.88983001 -2.3203469  -1.00239543]
 [ 0.13873771 -0.22112471 -0.02846577 -0.79207229]
 [ 0.21203089 -0.66870531  2.34881267  1.79446772]]


In [10]:
y_pred = iris_model.predict(X_test)

In [11]:
iris_model.score(X_test, y_test)

0.9736842105263158